name: 'Hello World'
description: 'Greet someone and record the time'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  subcommand:
    description: todo
    required: false
    default: synchronous
  azure_storage_account_name:
    description: todo
    required: true
  azure_storage_container_name:
    description: todo
    required: true
  azure_storage_blob_name:
    description: todo
    required: false
    default: 'new'
  workflow_path:
    description: todo
    required: true
  workflow_inputs_path:
    description: todo
    required: true
  workflow_options_path:
    description: todo
    required: false
    default: null
  workflow_dependencies_path:
    description: todo
    required: true
  workflow_id:
    description: tobe used only for the monitor task
    required: false
    default: null
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'dist/index.js'
