name: 'Cromwell Automation TEST0011'
description: 'Automates the submission and monitoring of WDL workflows to a Cromwell server.'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  subcommand:
    description: todo
    required: false
    default: synchronous
  azure_storage_account_name:
    description: todo
    required: true
  azure_storage_container_name:
    description: todo
    required: true
  azure_storage_inputs_container_name:
    description: todo
    required: true
  azure_storage_blob_name:
    description: todo
    required: false
    default: 'new'
  azure_storage_metadata_container_name:
    description: todo
    required: false
    default: 'outputs'
  workflow_path:
    description: todo
    required: true
  workflow_inputs_path:
    description: todo
    required: true
  workflow_options_path:
    description: todo
    required: false
    default: null
  workflow_dependencies_path:
    description: todo
    required: true
  workflow_id:
    description: tobe used only for the monitor task
    required: false
    default: null
runs:
  using: 'node20'
  main: 'dist/index.js'
