name: 'Hello World'
description: 'Greet someone and record the time'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  subcommand:
    description: todo
    required: false
    default: synchronous
  azure-storage-account-name:
    description: todo
    required: true
  azure-storage-container-name:
    description: todo
    required: true
  azure-storage-blob-name:
    description: todo
    required: true
  workflow-path:
    description: todo
    required: true
  workflow-inputs-path:
    description: todo
    required: true
  workflow-options-path:
    description: todo
    required: false
    default: null
  workflow-dependencies-path:
    description: todo
    required: true
  workflow-id:
    description: tobe used only for the monitor task
    required: false
    default: null
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'dist/index.js'
